steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/falcon-mcp/falcon-mcp-server:${SHORT_SHA}',
    '--file', 'Dockerfile',
    '.'
  ]
  env:
  - 'DOCKER_BUILDKIT=1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/${PROJECT_ID}/falcon-mcp/falcon-mcp-server:${SHORT_SHA}']

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'asia-south1-docker.pkg.dev/${PROJECT_ID}/falcon-mcp/falcon-mcp-server:${SHORT_SHA}'
