steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/falcon-mcp/${_SERVICE_NAME}:${COMMIT_SHA}',
    '--file', 'Dockerfile',
    '.'
  ]
  env:
  - 'DOCKER_BUILDKIT=1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/falcon-mcp/${_SERVICE_NAME}:${COMMIT_SHA}']

images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/falcon-mcp/${_SERVICE_NAME}:${COMMIT_SHA}'
